# -*- coding: utf-8 -*-
"""
Created on Wed Jan  3 16:45:32 2024

@author: Valentina Espinoza
"""

import numpy as np


def bouguer_disk(thickness, radius, height, density):
    """
    This function uses the Bouguer formula to compute the gravity signal 
    generated by a disk of finite radius at a point above its center.
    Based on Eq. 5.112 from Turcotte & Schubert (2002). 

    Parameters
    ----------
    thickness : float
        Thickness of the disk, expressed in meters.
    radius : float
        Radius of the disk, expressed in meters.
    height : float
        Height (above the disk) where the gravity signal is desired, expressed
        in meters.
    density : float
        Density of the disk, expressed in kg/m^3

    Returns
    -------
    gravitational_acceleration : float
        Strength of the downward gravitational acceleration generated by the 
        disk, expressed in m/s2.

    """

    G = 6.6742e-11

    r = radius
    rho = density
    b = height
    h = np.abs(thickness)

    gravitational_acceleration = (2 * np.pi * G * rho) * (h + (b**2 + r**2)**0.5 - ((b + h)**2 + r**2)**0.5)
    return gravitational_acceleration



if __name__ == "__main__":
    
    # Example usage:
    thickness = 5e3
    radius = 20 * 110e3
    height = 0
    density = 2700
    
    gravitational_acceleration = bouguer_disk(thickness, radius, height, density)
    print("gravitational_acceleration: ", gravitational_acceleration)