# -*- coding: utf-8 -*-
"""
Created on Wed Jan  3 16:45:32 2024

@author: Valentina Espinoza
"""

import numpy as np


def bouguer_disk(thickness, radius, height, density):
    """
    This function uses the Bouguer formula to compute the gravity signal 
    generated by a disk of finite radius at a point above its center.

    Parameters
    ----------
    thickness : float
        Thickness of the disk, expressed in meters.
    radius : float
        Radius of the disk, expressed in meters.
    height : float
        Height (above the disk) where the gravity signal is desired, expressed
        in meters.
    density : float
        Density of the disk, expressed in kg/m^3

    Returns
    -------
    gravitational_acceleration : float
        Strenght of the downward gravitational acceleration generated by the 
        disk, expressed in mGal.

    """

    G = 6.6742e-11

    R = radius
    rho = density
    b = height
    thk = np.abs(thickness)

    gravitational_acceleration = np.sign(thickness) * ((2 * np.pi * G) * rho * (thk + (R**2 + b**2)**0.5 - (R**2 + (b + thk)**2)**0.5) / 1e-5)

    return gravitational_acceleration



if __name__ == "__main__":
    
    thickness = 
    radius = 
    height = 
    density = 2700
    
    gravitational_acceleration = bouguer_disk(thickness, radius, height, density)
    print("gravitational_acceleration: ", gravitational_acceleration)